name: my_connection
description: 'A new Flutter project.'

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.11.0
  clock: ^1.1.2
  rxdart: ^0.28.0
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5
  jiffy: ^6.2.1
  intl: ^0.20.2

  # cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.2.2

  # google
  google_sign_in: ^7.1.1
  google_fonts: ^6.1.0

  # Animation
  swipeable_page_route: ^0.4.7
  animations: ^2.0.11

  # Network
  dio: ^5.8.0+1

  # Translation
  slang: ^4.7.3
  slang_flutter: ^4.7.0

  # Generate
  get_it: ^8.0.3
  retrofit: ^4.0.1
  injectable: ^2.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Env management
  package_info_plus: ^8.3.0
  flutter_dotenv: ^5.2.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_remote_config: ^5.5.0

  # Debugging tools
  flutter_fimber: ^0.7.1

  # Proxy overrides
  system_proxy: ^0.1.0
  

dev_dependencies:
  flutter_lints: ^6.0.0

  # Generate
  freezed: ^3.1.0
  injectable_generator: ^2.4.0
  retrofit_generator: ^9.7.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  slang_build_runner: ^4.7.0
  flutter_gen_runner: ^5.3.1

  analyzer: ^7.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/fonts/
    - assets/json/
    - develop.env
    - production.env

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
